"""Initial migration

Revision ID: b45e5a7eb0bb
Revises: c7d0d6e578a7
Create Date: 2024-12-03 19:56:53.431222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b45e5a7eb0bb'
down_revision: Union[str, None] = 'c7d0d6e578a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
