# Generated by Django 4.2.16 on 2024-11-30 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО менеджера')),
                ('department', models.CharField(max_length=100, verbose_name='Подразделение')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время публикации')),
                ('payer', models.CharField(max_length=10, verbose_name='Плательщик')),
                ('sender', models.CharField(max_length=100, verbose_name='Отправитель')),
                ('recipient', models.CharField(max_length=100, verbose_name='Получатель')),
                ('description', models.TextField(verbose_name='Содержание задания')),
                ('urgency', models.CharField(max_length=10, verbose_name='Срочность')),
                ('invoice', models.CharField(max_length=15, verbose_name='Номер накладной')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistic.manager', verbose_name='Менеджер')),
            ],
        ),
    ]
